"use client";

import Image from "next/image";
import { Eye, FileDown, ShieldCheck } from "lucide-react";
import { PREVIEW_CUSTOMER, formatPreviewPrice, previewLines } from "@/lib/proposals/preview-data";
import { studioProduct } from "@/lib/proposals/template-studio";
import type { V2Section, V2Template } from "./v2-templates-panel";

function text(section: V2Section | undefined, language: "tr" | "en", fallback: string) {
  return (language === "tr" ? section?.body_tr : section?.body_en) || fallback;
}
function title(section: V2Section | undefined, language: "tr" | "en", fallback: string) {
  return (language === "tr" ? section?.title_tr : section?.title_en) || fallback;
}
function scope(section: V2Section | undefined, language: "tr" | "en", field: "included" | "excluded", fallback: string[]) {
  const value = section?.content?.[`${field}_${language}`];
  return Array.isArray(value) && value.filter((item): item is string => typeof item === "string" && item.trim().length > 0).length > 0 ? value.filter((item): item is string => typeof item === "string" && item.trim().length > 0) : fallback;
}

export function TemplatePreview({ template }: { template: V2Template }) {
  const product = studioProduct(template.product); const language = template.language; const tr = language === "tr";
  const find = (sectionType: string) => template.sections.find((section) => section.section_type === sectionType);
  const rows = previewLines(template.product); const currencies = Array.from(new Set(rows.map((row) => row.currency)));
  const included = scope(find("scope"), language, "included", tr ? ["Kuruma özel keşif ve çözüm tasarımı", "Yönetici başlangıç eğitimi", "Canlıya geçiş ve başarı takibi"] : ["Discovery and solution design", "Administrator onboarding", "Go-live and success follow-up"]);
  const excluded = scope(find("scope"), language, "excluded", tr ? ["Kapsam dışı özel geliştirmeler", "Üçüncü taraf lisans ve altyapı bedelleri"] : ["Out-of-scope custom development", "Third-party license and infrastructure fees"]);
  return <section className="overflow-hidden rounded-2xl border border-rg-line bg-rg-surface shadow-rg">
    <header className="flex flex-wrap items-center justify-between gap-3 border-b border-rg-line bg-rg-surface-alt px-5 py-3"><div className="flex items-center gap-2"><Eye className="h-4 w-4 text-primary" /><div><h2 className="text-[13px] font-bold text-rg-ink">Tam belge önizlemesi</h2><p className="text-[11px] text-rg-ink-faint">Örnek müşteri, fiyat ve kapsam verisiyle HTML teklif görünümü</p></div></div><span className="inline-flex items-center gap-1.5 rounded-lg border border-rg-line bg-rg-surface px-3 py-1.5 text-[11px] font-semibold text-rg-ink-soft"><FileDown className="h-3.5 w-3.5" />PDF çıktısında aynı yapı kullanılır</span></header>
    <div className="bg-slate-100 p-4 sm:p-7"><article className="mx-auto max-w-[760px] overflow-hidden rounded-sm bg-white shadow-[0_12px_35px_rgba(15,23,42,.16)]">
      <div className="relative min-h-[265px] overflow-hidden bg-[#0c1938] p-7 text-white sm:p-10">{product.coverImage && <Image src={product.coverImage} alt="" fill sizes="760px" className="object-cover opacity-25" />}<div className="absolute inset-0 bg-gradient-to-br from-[#0b1633] via-[#0b1633]/75 to-transparent" /><div className="relative"><div className="text-[10px] font-bold tracking-[.18em] text-white/65">RESPONGO · {PREVIEW_CUSTOMER.reference}</div><p className="mt-12 text-[12px] text-white/70">{tr ? "HAZIRLANAN" : "PREPARED FOR"}</p><h3 className="mt-2 font-display text-3xl font-bold leading-tight">{PREVIEW_CUSTOMER.company}</h3><p className="mt-6 max-w-md text-[14px] leading-6 text-white/85">{text(find("cover"), language, tr ? `Kurumunuza özel ${product.label} çözüm önerisi` : `A tailored ${product.label} solution proposal`)}</p><div className="mt-8 flex gap-8 text-[11px] text-white/65"><span>{tr ? "Hazırlayan" : "Prepared by"}<strong className="mt-1 block text-white">{PREVIEW_CUSTOMER.preparedBy}</strong></span><span>{tr ? "Geçerlilik" : "Valid until"}<strong className="mt-1 block text-white">{PREVIEW_CUSTOMER.validUntil}</strong></span></div></div></div>
      <div className="space-y-9 p-7 sm:p-10"><section><p className="text-[10px] font-bold tracking-[.14em] text-primary">01 · {title(find("customer_info"), language, tr ? "MÜŞTERİ BİLGİLERİ" : "CUSTOMER DETAILS")}</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><div className="rounded-lg bg-slate-50 p-3"><span className="text-[10px] text-slate-500">{tr ? "Kurum" : "Organisation"}</span><strong className="mt-1 block text-[13px] text-slate-800">{PREVIEW_CUSTOMER.company}</strong></div><div className="rounded-lg bg-slate-50 p-3"><span className="text-[10px] text-slate-500">{tr ? "İrtibat" : "Contact"}</span><strong className="mt-1 block text-[13px] text-slate-800">{PREVIEW_CUSTOMER.contact}</strong></div></div></section>
      <section><p className="text-[10px] font-bold tracking-[.14em] text-primary">02 · {title(find("product_info"), language, tr ? "ÇÖZÜM ÖZETİ" : "SOLUTION OVERVIEW")}</p><h4 className="mt-3 font-display text-xl font-bold text-slate-900">{tr ? product.trName : product.enName}</h4><p className="mt-2 whitespace-pre-wrap text-[13px] leading-6 text-slate-600">{text(find("product_info"), language, tr ? `${product.trName}, öğrenme stratejinizi ölçülebilir iş sonuçlarına bağlayan bütünleşik bir deneyim sunar.` : `${product.enName} connects your learning strategy to measurable business outcomes.`)}</p></section>
      <section className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-emerald-100 bg-emerald-50/50 p-4"><h4 className="text-[12px] font-bold text-emerald-800">{tr ? "Teklife dahil" : "Included"}</h4><ul className="mt-3 space-y-2 text-[12px] leading-5 text-emerald-950">{included.map(item => <li key={item}>✓ {item}</li>)}</ul></div><div className="rounded-xl border border-amber-100 bg-amber-50/50 p-4"><h4 className="text-[12px] font-bold text-amber-800">{tr ? "Teklife dahil değil" : "Excluded"}</h4><ul className="mt-3 space-y-2 text-[12px] leading-5 text-amber-950">{excluded.map(item => <li key={item}>– {item}</li>)}</ul></div></section>
      <section><p className="text-[10px] font-bold tracking-[.14em] text-primary">03 · {tr ? "YATIRIM ÖZETİ" : "INVESTMENT SUMMARY"}</p><div className="mt-3 overflow-hidden rounded-xl border border-slate-200"><table className="w-full text-left"><thead className="bg-slate-50 text-[10px] uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-2">{tr ? "Kalem" : "Item"}</th><th className="px-3 py-2 text-center">{tr ? "Adet" : "Qty"}</th><th className="px-3 py-2 text-right">{tr ? "Tutar" : "Amount"}</th></tr></thead><tbody>{rows.map(row => <tr key={row.name} className="border-t border-slate-100"><td className="px-3 py-3"><strong className="block text-[12px] text-slate-800">{row.name}</strong><span className="text-[10px] text-slate-500">{row.description}</span></td><td className="px-3 py-3 text-center text-[12px] text-slate-600">{row.quantity}</td><td className="px-3 py-3 text-right text-[12px] font-semibold text-slate-800">{formatPreviewPrice(row.quantity * row.unitPrice, row.currency)}</td></tr>)}</tbody></table></div><div className="mt-3 flex flex-wrap justify-end gap-2">{currencies.map(currency => <div key={currency} className="rounded-lg bg-slate-900 px-4 py-2 text-right text-white"><span className="block text-[9px] uppercase text-slate-300">{tr ? "Toplam yatırım" : "Total investment"}</span><strong className="text-[15px]">{formatPreviewPrice(rows.filter(row => row.currency === currency).reduce((sum, row) => sum + row.quantity * row.unitPrice, 0), currency)}</strong></div>)}</div></section>
      <section><p className="text-[10px] font-bold tracking-[.14em] text-primary">04 · {tr ? "UYGULAMA PLANI" : "IMPLEMENTATION PLAN"}</p><div className="mt-3 grid grid-cols-3 gap-2 text-center text-[11px]"><div className="rounded-lg bg-slate-50 p-3"><strong className="block text-primary">1. Hafta</strong><span className="mt-1 block text-slate-500">{tr ? "Keşif ve plan" : "Discovery"}</span></div><div className="rounded-lg bg-slate-50 p-3"><strong className="block text-primary">2–3. Hafta</strong><span className="mt-1 block text-slate-500">{tr ? "Kurulum ve test" : "Configuration"}</span></div><div className="rounded-lg bg-slate-50 p-3"><strong className="block text-primary">4. Hafta</strong><span className="mt-1 block text-slate-500">{tr ? "Canlıya geçiş" : "Go-live"}</span></div></div></section>
      <section className="rounded-xl border border-slate-200 p-4"><div className="flex gap-2"><ShieldCheck className="h-4 w-4 shrink-0 text-primary" /><div><h4 className="text-[12px] font-bold text-slate-800">{tr ? "Ticari şartlar ve onay" : "Commercial terms and acceptance"}</h4><p className="mt-1 text-[11px] leading-5 text-slate-600">{tr ? "Bu örnek teklif 30 gün geçerlidir. Vergiler, gerekli üçüncü taraf lisansları ve kapsam dışı işler ayrıca değerlendirilir. Nihai şartlar tarafların yazılı sözleşmesiyle kesinleşir." : "This sample proposal is valid for 30 days. Taxes, required third-party licenses and out-of-scope work are assessed separately. Final terms are governed by the parties' written agreement."}</p></div></div></section>
      <footer className="border-t border-slate-100 pt-5 text-[10px] text-slate-400">Respongo · Learning technologies for measurable performance · {PREVIEW_CUSTOMER.reference}</footer></div>
    </article></div>
  </section>;
}
