-- Teklif şablonlarına ürün bazlı kapsam ve çözüm anlatımı ekler.
-- Yeni şablonlarda da aynı metinler başlangıç içeriği olarak kullanılmalıdır.
with product_copy(product, tr_body, en_body, included_tr, included_en) as (
  values
  ('golms', 'Bulut tabanlı LMS; rol bazlı katalog, SCORM/xAPI, sınav ve sertifika, raporlama, çoklu dil, SSO ve HRIS entegrasyonlarıyla öğrenme operasyonunu merkezi yönetir.', 'Cloud LMS with role-based catalogues, SCORM/xAPI, assessments, certificates, reporting, multilingual delivery, SSO and HRIS integrations.', '["Keşif ve çözüm tasarımı","Kurulum, rol ve katalog yapılandırması","Yönetici eğitimi ve 30 günlük başarı takibi"]'::jsonb, '["Discovery and solution design","Configuration of roles and catalogue","Administrator training and 30-day success follow-up"]'::jsonb),
  ('golxp', 'Yetkinlik mimarisi, kişiselleştirilmiş öğrenme yolculukları, Skills Intelligence, Neura AI, beceri analitiği ve yönetici içgörüleriyle çalışan deneyimini güçlendirir.', 'Builds employee experience through capability architecture, personalised journeys, Skills Intelligence, Neura AI, skills analytics and manager insights.', '["Yetkinlik keşfi","Başlangıç öğrenme yolculukları","Yönetici içgörüleri eğitimi"]'::jsonb, '["Capability discovery","Initial learning journeys","Manager insights onboarding"]'::jsonb),
  ('gocatalog', 'Teknik, liderlik, uyum ve yapay zekâ becerilerinde çok dilli hazır içerik erişimini GOLMS ve GOLXP ekosistemiyle birleştirir.', 'Combines multilingual ready-to-use content across technical, leadership, compliance and AI skills with the GOLMS and GOLXP ecosystem.', '["Katalog keşfi ve eşleştirme","SSO ve katalog entegrasyonu","Kullanım ve benimseme raporu"]'::jsonb, '["Catalogue discovery and matching","SSO and catalogue integration","Usage and adoption report"]'::jsonb),
  ('gofactory', 'Öğrenme hedefinden senaryo, tasarım, seslendirme, etkileşim, SCORM paketi ve kalite kabulüne kadar uçtan uca özel dijital içerik üretir.', 'Delivers bespoke digital learning from learning design and scripting through production, interaction, SCORM packaging and quality acceptance.', '["Öğrenme tasarımı ve senaryo","Görsel üretim ve etkileşim","SCORM teslimi ve kabul testi"]'::jsonb, '["Learning design and scripting","Visual production and interaction","SCORM delivery and acceptance test"]'::jsonb),
  ('gotools', 'Kurum içi ekiplerin video, animasyon, etkileşimli kurs ve mikro öğrenme üretmesini marka, erişilebilirlik ve yayın standartlarıyla destekler.', 'Enables in-house teams to create video, animation, interactive courses and microlearning under brand, accessibility and publishing standards.', '["Araç kurulumu ve yönetici yapılandırması","Yazar başlangıç eğitimi","Yayın standartları ve kalite kontrolü"]'::jsonb, '["Tool setup and administrator configuration","Author onboarding","Publishing standards and quality control"]'::jsonb),
  ('general', 'Respongo öğrenme stratejisini içerik, deneyim, teknoloji ve ölçüm katmanlarıyla tek program mimarisinde birleştirir.', 'Respongo brings content, experience, technology and measurement together in one learning programme architecture.', '["Program keşfi","Çözüm mimarisi","Fazlı canlıya geçiş planı"]'::jsonb, '["Programme discovery","Solution architecture","Phased go-live plan"]'::jsonb)
)
update public.proposal_template_sections s
set body_tr = case when t.language = 'tr' then c.tr_body else s.body_tr end,
    body_en = case when t.language = 'en' then c.en_body else s.body_en end,
    content = case when s.section_type = 'scope' then s.content || jsonb_build_object('included_tr', c.included_tr, 'included_en', c.included_en, 'excluded_tr', jsonb_build_array('Kapsam dışı özel geliştirmeler', 'Üçüncü taraf lisansları ve altyapı maliyetleri'), 'excluded_en', jsonb_build_array('Out-of-scope custom development', 'Third-party licenses and infrastructure costs')) else s.content end
from public.proposal_templates t
join product_copy c on c.product = coalesce(t.product::text, 'general')
where s.template_id = t.id and s.section_type in ('product_info', 'scope');
