-- Kullanıcının onayladığı Respongo Fiyat Listesi 2026'nin eksiksiz kalemleri.
do $$
declare v_golms uuid; v_factory uuid; v_tools_usd uuid; v_tools_try uuid;
begin
  insert into public.price_lists (name, product, currency, is_active, valid_from, valid_until) values
    ('GOLMS — Resmi Lisans 2026', 'golms', 'USD', true, '2026-01-01', '2026-12-31') returning id into v_golms;
  insert into public.price_list_items (price_list_id,name,description,unit,unit_price) values
    (v_golms,'100 kullanıcı','Bulut tabanlı yazılım lisansı','yıl',2000),(v_golms,'250 kullanıcı','Bulut tabanlı yazılım lisansı','yıl',3000),(v_golms,'500 kullanıcı','Bulut tabanlı yazılım lisansı','yıl',5000),(v_golms,'1.000 kullanıcı','Bulut tabanlı yazılım lisansı','yıl',8500),(v_golms,'2.500 kullanıcı','Bulut tabanlı yazılım lisansı','yıl',13000),(v_golms,'5.000 kullanıcı','Bulut tabanlı yazılım lisansı','yıl',19000),(v_golms,'10.000 kullanıcı','Bulut tabanlı yazılım lisansı','yıl',25000),
    (v_golms,'Iyzico entegrasyonu','Tek seferlik kurulum','proje',1800),(v_golms,'SSL standart güvenlik','1 domain, yıllık maliyet','yıl',450),(v_golms,'SSL premium güvenlik','1 domain, yıllık maliyet','yıl',6500),(v_golms,'Video akış hizmeti','Amazon S3, ek 1 GB depolama','yıl',78),(v_golms,'HTML5 içerik geliştirme aracı entegrasyonu','Yıllık entegrasyon','yıl',1500),(v_golms,'SMS API entegrasyonu','Tek seferlik entegrasyon','proje',1800),(v_golms,'Sanal sınıf entegrasyonu','Tek seferlik entegrasyon','proje',600),(v_golms,'Ek dil · Arapça','İlave dil lisansı','yıl',1000),(v_golms,'Ek dil · Fransızca','İlave dil lisansı','yıl',1000),(v_golms,'Ek dil · Çince','İlave dil lisansı','yıl',1000),(v_golms,'Ek dil · Hintçe','İlave dil lisansı','yıl',1000),(v_golms,'Ek dil · Vietnamca','İlave dil lisansı','yıl',1000),(v_golms,'Ek dil · Tayca','İlave dil lisansı','yıl',1000);

  insert into public.price_lists (name,product,currency,is_active,valid_from,valid_until) values ('GOFACTORY — Resmi İçerik Hizmetleri 2026','gofactory','TRY',true,'2026-01-01','2026-12-31') returning id into v_factory;
  insert into public.price_list_items (price_list_id,name,description,unit,unit_price) values
    (v_factory,'Video ve animasyon · 30 dk','Referans proje bedeli','proje',300000),(v_factory,'Sanal gerçeklik · 30 dk','Referans proje bedeli','proje',700000),(v_factory,'Oyun ve simülasyon · 30 dk','Referans proje bedeli','proje',1250000),(v_factory,'Mobil öğrenme · 30 dk','Referans proje bedeli','proje',490000),(v_factory,'ILT · 60 dk · İstanbul','Eğitmen liderliğinde eğitim','oturum',45000),(v_factory,'VILT · 60 dk','Sanal eğitmen liderliğinde eğitim','oturum',35000);

  insert into public.price_lists (name,product,currency,is_active,valid_from,valid_until) values ('GOTOOLS — Resmi SaaS 2026','gotools','USD',true,'2026-01-01','2026-12-31') returning id into v_tools_usd;
  insert into public.price_list_items (price_list_id,name,description,unit,unit_price) values
    (v_tools_usd,'Vyond Starter','Video ve animasyon aracı','yıl',699),(v_tools_usd,'Vyond Professional','Video ve animasyon aracı','yıl',1199),(v_tools_usd,'Vyond Enterprise','Video ve animasyon aracı','yıl',1649),(v_tools_usd,'Vyond Agency','Video ve animasyon aracı','yıl',1999),(v_tools_usd,'Powtoon Lite','Video ve animasyon aracı','yıl',180),(v_tools_usd,'Powtoon Pro+','Video ve animasyon aracı','yıl',840),(v_tools_usd,'Powtoon Advanced','Video ve animasyon aracı','yıl',1500),(v_tools_usd,'iSeazy Author Pro','Eğitim yazarlık aracı','yıl',864),(v_tools_usd,'iSeazy Author Business','Eğitim yazarlık aracı','yıl',2244),(v_tools_usd,'Craft Business','Eğitim yazarlık aracı','yıl',1188);
  insert into public.price_lists (name,product,currency,is_active,valid_from,valid_until) values ('GOTOOLS — JivoChat 2026','gotools','TRY',true,'2026-01-01','2026-12-31') returning id into v_tools_try;
  insert into public.price_list_items (price_list_id,name,description,unit,unit_price) values (v_tools_try,'JivoChat Professional · 1 temsilci','Canlı destek aracı','yıl',9240),(v_tools_try,'JivoChat Premium · 1 temsilci','Canlı destek aracı','yıl',13440),(v_tools_try,'JivoChat Corporate · 1 temsilci','Canlı destek aracı','yıl',18480);
end $$;
